#!/usr/bin/env python

# 
# Copyright (c) 2012 - 2014 TideSDK contributors 
# http://www.tidesdk.org
# Includes modified sources under the Apache 2 License
# Copyright (c) 2008 - 2012 Appcelerator Inc
# Refer to LICENSE for details of distribution and use.
# 

from os import path
Import('build env module')

env.Append(CPPDEFINES = ('TIDESDK_PROCESS_API_EXPORT', 1))

build.add_thirdparty(env, 'poco')
sources = Glob('*.cpp')
if build.is_win32():
    env.Append(CCFLAGS=['/MD', '/DUNICODE', '/D_UNICODE'])
    sources += Glob('win32/*.cpp')
else:
    sources += Glob('posix/*.cpp')

if build.is_win32():
    env.Append(CCFLAGS=['/DUNICODE', '/D_UNICODE'])

build.mark_build_target(build.utils.CopyTree(Glob('*.js'), module.dir))
build.mark_build_target(env.SharedLibrary(
    path.join(module.dir, 'tideprocess'), sources))
