#!/usr/bin/env python

# 
# Copyright (c) 2012 - 2014 TideSDK contributors 
# http://www.tidesdk.org
# Includes modified sources under the Apache 2 License
# Copyright (c) 2008 - 2012 Appcelerator Inc
# Refer to LICENSE for details of distribution and use.
# 


from os import path
Import('build env module')

env.Append(CPPDEFINES=('TIDESDK_PYTHON_API_EXPORT', 1))

build.add_thirdparty(env, 'poco')
if build.is_osx():
    env.Append(CPPPATH=['/System/Library/Frameworks/Python.framework/Versions/Current/Headers',build.tide_include_dir])
    env.Append(FRAMEWORKS=['Python'])

elif build.is_linux():
    env.Append(CPPPATH=[
        '${PYTHON_INCLUDE}',
        '/usr/lib/python/2.7/i386-linux',
        '/usr/include/python2.7',
        build.tide_include_dir])
    env.Append(LIBS=['python${PYTHON_VERSION}'])
    env.Append(CXXFLAGS = ['-Wno-unused-but-set-variable'])

elif build.is_win32():
    env.Append(CPPPATH=[build.tp('python', 'include')])
    env.Append(LIBPATH=[build.tp('python', 'libs')])
    env.Append(LIBS=['python27'])
    env.Append(CCFLAGS = ['/MD'])

build.mark_build_target(env.SharedLibrary(
    path.join(module.dir, 'tidepython'), Glob('*.cpp')))
if build.is_win32():
    build.utils.LightWeightCopy(build.tp('python'), module.dir)
