#!/usr/bin/env python

# 
# Copyright (c) 2012 - 2014 TideSDK contributors 
# http://www.tidesdk.org
# Includes modified sources under the Apache 2 License
# Copyright (c) 2008 - 2012 Appcelerator Inc
# Refer to LICENSE for details of distribution and use.
# 

from os import path
Import('build build_module_from_directory')

# These each have their own line because we can comment
# them out easily if we need temporarily disable one.
for dir in [
    'app', 
    'ui',
    'network',
    'filesystem',
    'media',
    'platform',
    'process',
    'monkey',
    'database',
    'worker',
    'codec',
    'socket',
]:
    build_module_from_directory(dir)
