#!/usr/bin/env python

# 
# Copyright (c) 2012 - 2014 TideSDK contributors 
# http://www.tidesdk.org
# Includes modified sources under the Apache 2 License
# Copyright (c) 2008 - 2012 Appcelerator Inc
# Refer to LICENSE for details of distribution and use.
# 

import os.path as p
Import('build')

script = p.join(build.os, 'SConscript')
build_dir = p.join(build.dir, 'objs', 'installer')
SConscript(script, variant_dir=build_dir, duplicate=0)
