#!/usr/bin/env python

# 
# Copyright (c) 2012 - 2014 TideSDK contributors 
# http://www.tidesdk.org
# Includes modified sources under the Apache 2 License
# Copyright (c) 2008 - 2012 Appcelerator Inc
# Refer to LICENSE for details of distribution and use.
# 


import os, os.path as path
Import('build','LIBUTILS_NAME')

env = build.env.Clone()
env.Append(CPPDEFINES=['USE_NO_EXPORT=1', 'UNICODE=1', '_UNICODE=1'])

env.Append(LIBS=[LIBUTILS_NAME])
env.Append(LIBPATH=[path.join(build.dir, 'objs')])

env.Append(LIBS=[
    'msi',
    'user32',
    'shell32',
    'iphlpapi',
    'advapi32',
    'wininet',
    'urlmon',
    'ole32',
    'gdi32'
])


build.add_thirdparty(env, 'boost_include')
# Common sources for both the MSI DLL and the update installer.
sources = ["common.cpp"]

build.mark_build_target(env.Program(
    path.join(build.dir, 'sdk', 'installer', 'installer.exe'),
    sources + ['progress_dialog.cpp', 'update_installer.cpp']))

# Statically-link the MSI DLL.
#ccf = env['CCFLAGS'][:]
#if '/MD' in ccf:
#    ccf.remove('/MD')
#ccf.append('/MT')
#env['CCFLAGS'] = ccf

env.Append(LIBS=['msi']); # Add the MSI lib.
build.mark_build_target(env.SharedLibrary(path.join(build.dir, 'sdk', 'installer', 'tide_installer'),
    sources + ['tide_actions.cpp']))
