#!/usr/bin/env python

# 
# Copyright (c) 2012 - 2014 TideSDK contributors 
# http://www.tidesdk.org
# Includes modified sources under the Apache 2 License
# Copyright (c) 2008 - 2012 Appcelerator Inc
# Refer to LICENSE for details of distribution and use.
# 

import os.path as path

Import('build','LIBUTILS_NAME')

Env = build.env.Clone()
Env.Append(LIBS=[LIBUTILS_NAME])
Env.Append(LIBPATH=[path.join(build.dir, 'objs')])
Env.Append(LIBS='libz')
Env.ParseConfig('pkg-config --cflags --libs gtk+-2.0 gdk-2.0 gthread-2.0 libcurl')
build.mark_build_target(Env.Program(
    path.join(build.dir, 'sdk', 'installer', 'installer'),
    Glob('*.cpp')))
