#!/usr/bin/env python

# 
# Copyright (c) 2012 - 2014 TideSDK contributors 
# http://www.tidesdk.org
# Includes modified sources under the Apache 2 License
# Copyright (c) 2008 - 2012 Appcelerator Inc
# Refer to LICENSE for details of distribution and use.
# 

from os import path
Import('build env module')

env.Append(CPPDEFINES = ('TIDESDK_PLATFORM_API_EXPORT', 1))
build.add_thirdparty(env, 'poco')

if build.is_win32():
    build.add_thirdparty(env, 'cairo')
    env.Append(CCFLAGS=['/MD', '/DUNICODE', '/D_UNICODE'])
    env.Append(LIBS=['Advapi32', 'Iphlpapi', 'user32', 'shell32', 'gdi32'])
    env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN',1))

elif build.is_osx():
    env.Append(FRAMEWORKS = ['AppKit', 'Cocoa'])

elif build.is_linux():
    env.ParseConfig('pkg-config --cflags --libs gdk-2.0 x11')

sources = [File('platform_module.cpp'), File('platform_binding.cpp')]
if build.is_osx():
    sources.append(File('platform_binding_%s.mm' % build.os))
else:
    sources.append(File('platform_binding_%s.cpp' % build.os))

build.mark_build_target(env.SharedLibrary(
    path.join(module.dir, 'tideplatform'), sources))
