#!/usr/bin/env python

# 
# Copyright (c) 2012 - 2014 TideSDK contributors 
# http://www.tidesdk.org
# Includes modified sources under the Apache 2 License
# Copyright (c) 2008 - 2012 Appcelerator Inc
# Refer to LICENSE for details of distribution and use.
# 

from os import path
from tide import Module
Import('build')

def build_module_from_directory(dir):
    name = dir.lower().replace('.', '')
    module = Module(name, build.version, path.join(build.dir, 'modules', name))
    build.modules.append(module)

    env = build.env.Clone()
    env.Append(CPPDEFINES=[('MODULE_NAME', name), ('MODULE_VERSION', build.version)])

    SConscript(
        path.join(dir, 'SConscript'),
        variant_dir=path.join(build.dir, 'objs', 'modules', name),
        exports='build module env',
        duplicate=0)

Export('build_module_from_directory')

if not build.tidelite:
    for dir in ['python', 'ruby', 'php']:
        build_module_from_directory(dir)
